### PR TITLE
added greet bot for new pull_request and issue

### LINKED ISSUE #35: Create greeting bot using Github Actions for new pull requests and issues
## Background
We'd like to add a greeting bot that provides a comment when a new pull request or issue is made

# Solution
Use Github Actions to create a greeting bot for new issues and new pull requests in the Open-Sentencing repository.

Learn more about Github Actions [here](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#create-an-example-workflow):

## Tasks
- Use [this greeting bot an example ](
https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/main/.github/workflows/greetings.yml)
- Read about Github Actions
- Create Github Action, title the yml file`greetings.yml`
- Test Github Action

## Acceptance criteria
- Github action is present in ./github/workflows folder in Open-Sentencing repo
- file is named `greetings.yml`
- greetings for PR and issue is as listed in [example](
https://github.com/Call-for-Code-for-Racial-Justice/Five-Fifths-Voter/blob/main/.github/workflows/greetings.yml)

### PR DESCRIPTION
**Pull request by DireWolf707**
Closes #35

### CODE REVIEW

**Comment by DireWolf707** [comment]
What changes are you asking for? Please specify

**Comment by siranjujugi** [comment]
> Sry, i dont understand what changes are you asking for? Please specify
> 
> I am new to open-source :(

I meant to see if you can change the word ASAP used in the below snippet as It finds an urgency which I felt was not necessary. Otherwise, I am fine with adding the greet. 

 pr-message: 'Thank you for your contribution! Someone will review it ASAP.'

**Comment by DireWolf707** [comment]
Changed word "ASAP" with "soon" 
i hope its okay now :)

**Comment by DireWolf707** [comment]
@siranjujugi Sry to disturb if you are busy to review changes right now but do let me know if I should add same github action to other code-for-racial-justice repos which require greet bot.

**Review by siranjujugi — APPROVED** [review]

**Pull request merged**
